  
```{r}
library(ggplot2)
library(zoo)
library(reshape2)
library(readr)
```

# Evolution

```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)

setwd("~/FLS2_engineering/R_ploting/script/")

# Load the data
fagales_data <- read.csv("../input/omega/fagales_M8_omega.csv")
rosales_data <- read.csv("../input/omega/rosales_M8_omega.csv")
brassicales_data <- read.csv("../input/omega/brassicales_M8_omega.csv")

# Define a function to calculate the distribution of dN/dS > 1 across regions
calculate_distribution <- function(data, regions) {
  distribution <- numeric(length(regions) - 1)
  total_high_dn_ds <- sum(data$dN.dS > 1)
  for (i in 1:(length(regions) - 1)) {
    count <- sum(data$dN.dS[data$pos >= regions[i] & data$pos < regions[i + 1]] > 1)
    portion <- ifelse(total_high_dn_ds > 0, count / total_high_dn_ds, 0)
    distribution[i] <- portion
  }
  return(distribution)
}

# Define the custom ggplot theme
my_ggplot_theme <- theme_classic() +
  theme(text = element_text(size = 16),
        axis.title.x = element_text(size = 14, color = "black"),
        axis.title.y = element_text(size = 14, color = "black"),
        axis.text.x = element_text(size = 14, color = "black"),
        axis.text.y = element_text(size = 14, color = "black"),
        axis.ticks = element_line(size = 0.8))


# Define the regions for each dataset (add an upper bound to the last region based on data)
fagales_regions <- c(71, 95, 119, 143, 167, 191, 215, 239, 263, 287, 311, 335, 359, 383, 407, 431, 455, 479, 503, 527, 551, 575, 601, 625, 649, 674, 698, 722, max(fagales_data$pos) + 1)


rosales_regions <- c(73, 97, 121, 145, 169, 193, 217, 241, 265, 289, 313, 337, 361, 385, 409, 433, 457, 481, 505, 529, 553, 577, 603, 627, 651, 676, 700, 725, max(rosales_data$pos) + 1)

brassicales_regions <- c(73, 97, 121, 145, 169, 193, 217, 241, 265, 289, 313, 337, 361, 385, 408, 432, 456, 480, 504, 528, 552, 576, 602, 626, 650, 677, 702, 726, max(brassicales_data$pos) + 1)

# Calculate distributions
fagales_dist <- calculate_distribution(fagales_data, fagales_regions)
rosales_dist <- calculate_distribution(rosales_data, rosales_regions)
brassicales_dist <- calculate_distribution(brassicales_data, brassicales_regions)

# Calculate average distribution
average_dist <- (fagales_dist + rosales_dist + brassicales_dist) / 3

# Prepare data for ggplot
regions <- as.factor(1:28)
data <- data.frame(regions, fagales_dist, rosales_dist, brassicales_dist, average_dist)

# Melt the data for ggplot
data_melted <- melt(data, id.vars = 'regions')

distribution <- ggplot() +
  geom_bar(data = data_melted[data_melted$variable != "average_dist", ], 
           aes(x = regions, y = value, fill = variable), 
           stat = "identity", position = position_dodge(width = 0.5), alpha = 0.7) +
  geom_line(data = data.frame(regions, average_dist = average_dist), 
            aes(x = regions, y = average_dist, group = 1), color = "black", size = 0.7, alpha = 0.5) +
  #geom_point(data = data.frame(regions, average_dist = average_dist), 
            # aes(x = regions, y = average_dist), color = "black", size = 2) +
  labs(x = "LRR", y = "Proportion of residues with omega > 1") +
  scale_x_discrete(breaks = regions) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.15))+
  scale_fill_manual(values = c("fagales_dist" = "#EF797E", "rosales_dist" = "#8DA0CB", "brassicales_dist" = "#FDCCA5")) +
  my_ggplot_theme 

print(distribution)
# Save the plot to a file
ggsave("../output/omega/omega_distribution_plot.pdf", plot = distribution, width = 13, height = 4, dpi = 300)


```



```{r}
write.csv(omega_data_combined, file = "../output/omega/combined_omega.csv")
```


####Plot raw dN/dS at region 1 LRR 7 & 8
```{r}
# Load data from CSV files
fagales_data <- read_csv("../input/omega/fagales_M8_omega.csv")
brassicales_data <- read_csv("../input/omega/brassicales_M8_omega.csv")
rosales_data <- read_csv("../input/omega/rosales_M8_omega.csv")

# Add 'Group' column to each dataset
fagales_data$Group <- 'Fagales'
brassicales_data$Group <- 'Brassicales'
rosales_data$Group <- 'Rosales'

# Define ranges for each group
fagales_range <- c(215, 262)
brassicales_range <- c(217, 264)
rosales_range <- c(217, 264)

# Function to extract data for a specified range and group
extract_data <- function(data, group_name, start_pos, end_pos) {
  data %>%
    filter(Group == group_name & pos >= start_pos & pos <= end_pos) %>%
    mutate(relative_pos = pos - start_pos + 1) # Create a new column for relative position
}

# Extract data for each range
fagales_data_region_1 <- extract_data(fagales_data, "Fagales", fagales_range[1], fagales_range[2])
brassicales_data_region_1 <- extract_data(brassicales_data, "Brassicales", brassicales_range[1], brassicales_range[2])
rosales_data_region_1 <- extract_data(rosales_data, "Rosales", rosales_range[1], rosales_range[2])

# Combine extracted data and set custom colors
combined_data <- rbind(
  fagales_data_region_1 %>% mutate(Group = "Fagales"),
  brassicales_data_region_1 %>% mutate(Group = "Brassicales"),
  rosales_data_region_1 %>% mutate(Group = "Rosales")
) %>% 
  mutate(color = ifelse(`dN/dS` > 1, case_when(
    Group == "Brassicales" ~ "#FDCCA5",
    Group == "Fagales" ~ "#EF797E",
    Group == "Rosales" ~ "#8DA0CB"
  ), case_when(
    Group == "Brassicales" ~ "gray75",
    Group == "Fagales" ~ "gray73",
    Group == "Rosales" ~ "gray77"
  )))

# Plot with custom color rules and a red line for dN/dS = 1
ggplot(combined_data, aes(x = relative_pos, y = `dN/dS`, fill = color)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.85) +
  geom_hline(yintercept = 1, color = "red", linetype = "dashed") +
  scale_fill_identity() + # Use the actual colors specified in the data frame
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 11, 25, 35, 48), labels = c("0"," ", "25", " ", "48")) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 3), breaks = seq(0, 3, by = 0.5)) + # Set y-axis limits and interval
  labs(x = "Amino Acid Position", y = "Posterior mean omega") +
  theme_classic() +
  theme(legend.position = "right",
       plot.margin = margin(t = 8, r = 8, b = 8, l = 8, unit = "pt"),  # Adjust top, right, bottom, and left margins
        axis.text.x = element_text(size = 15, color = "black"),
        axis.text.y = element_text(size = 15, color = "black"),
        axis.title.y = element_text(size = 15, color = "black"),
        axis.title.x = element_blank())
ggsave("../output/omega/raw_omega_region_1.pdf", width = 5.5, height = 3)

```

####Plot raw dN/dS at region 2 LRR 16 & 17
```{r}
# Define ranges for each group
fagales_range <- c(431, 478)
brassicales_range <- c(432, 479)
rosales_range <- c(433, 480)


# Extract data for each range
fagales_data_region_2 <- extract_data(fagales_data, "Fagales", fagales_range[1], fagales_range[2])
brassicales_data_region_2 <- extract_data(brassicales_data, "Brassicales", brassicales_range[1], brassicales_range[2])
rosales_data_region_2 <- extract_data(rosales_data, "Rosales", rosales_range[1], rosales_range[2])

# Combine extracted data and set custom colors
combined_data <- rbind(
  fagales_data_region_2 %>% mutate(Group = "Fagales"),
  brassicales_data_region_2 %>% mutate(Group = "Brassicales"),
  rosales_data_region_2 %>% mutate(Group = "Rosales")
) %>% 
  mutate(color = ifelse(`dN/dS` > 1, case_when(
    Group == "Brassicales" ~ "#FDCCA5",
    Group == "Fagales" ~ "#EF797E",
    Group == "Rosales" ~ "#8DA0CB"
  ), case_when(
    Group == "Brassicales" ~ "gray75",
    Group == "Fagales" ~ "gray73",
    Group == "Rosales" ~ "gray77"
  )))

# Plot with custom color rules and a red line for dN/dS = 1
ggplot(combined_data, aes(x = relative_pos, y = `dN/dS`, fill = color)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.85) +
  geom_hline(yintercept = 1, color = "red", linetype = "dashed") +
  scale_fill_identity() + # Use the actual colors specified in the data frame
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 11, 25, 35, 48), labels = c("0"," ", "25", " ", "48")) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 3), breaks = seq(0, 3, by = 0.5)) + # Set y-axis limits and interval
  labs(x = "Amino Acid Position", y = "Posterior mean omega" )+
  theme_classic() +
   theme(legend.position = "right",
          plot.margin = margin(t = 8, r = 8, b = 8, l = 8, unit = "pt"),  # Adjust top, right, bottom, and left margins
         axis.text.x = element_text(size = 15, color = "black"),
        axis.text.y = element_text(size = 15, color = "black"),
        axis.title.y = element_text(size = 15, color = "black"),
        axis.title.x = element_blank())
ggsave("../output/omega/raw_omega_region_2.pdf",  width = 5.5, height = 3)

```

#RCM

####Load RCM output matrix for fagales

```{r}
# Load necessary library
library(reshape2)

# Read the data from the file
file_path <- "../input/rcm/42_fagales_rcm_score" 
rcm_fagales <- read.csv(file_path, header = FALSE, sep = ",", strip.white = TRUE)

# Convert the data frame to a vector of values
values <- as.numeric(unlist(rcm_fagales))

# Ensure the length of values is compatible with a 14x28 matrix
if (length(values) != 14*28) {
  stop("The number of values in the file does not match the expected size of a 14x28 matrix.")
}

# Reshape the vector into a matrix
matrix_rcm_fagales <- matrix(values, ncol = 14, byrow = TRUE)

# If you need to manipulate or analyze the matrix, you can do so here.

# Optionally, write the matrix to a new CSV file if needed
write.csv(matrix_rcm_fagales, "../output/rcm/fagales_matrix_output.csv", row.names = FALSE)

```

####Plot the RCM plot for Fagales order

```{r}
# Load required libraries
library(ggplot2)
library(reshape2)  # For melt function
library(paletteer)

# Read the matrix data
matrix_rcm_fagales <- read.csv("../output//rcm/fagales_matrix_output.csv", header = TRUE)

# Create a new column 'Row' to preserve the row index before melting
matrix_rcm_fagales$Row <- seq_len(nrow(matrix_rcm_fagales))

# Melt the data for use with ggplot, with 'Row' as the id variable
matrix_rcm_fagales_melted <- melt(matrix_rcm_fagales, id.vars = 'Row')

# Define the color scale with blue for minimum and yellow for maximum
#blue_yellow_scale <- scale_fill_gradient2(low = "blue", mid = "green", high = "yellow", midpoint = 4, space = "Lab", transform = "identity")

# Create the heatmap
heatmap_plot <- ggplot(matrix_rcm_fagales_melted, aes(variable, Row, fill = value)) +
   geom_raster(interpolate = TRUE) +
  geom_tile(color = "darkgrey") +
  #blue_yellow_scale+
  #paletteer::scale_fill_paletteer_c("ggthemes::Orange-Blue Diverging", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::RdYlBu", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Spectral", direction = -1) +
 # paletteer::scale_fill_paletteer_c("oompaBase::blueyellow", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::topo.colors", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Plasma", direction = 1) +  # this is good
   #paletteer::scale_fill_paletteer_c("grDevices::ag_Sunset", direction = 1) +  # this is good
  # paletteer::scale_fill_paletteer_c("grDevices::YlOrRd", direction = 1) + # this is good
  #paletteer::scale_fill_paletteer_c("grDevices::YlGnBu", direction = 1) + # this is good
    #paletteer::scale_fill_paletteer_c("oompaBase::jetColors", direction = 1) + # this is perfect
    #paletteer::scale_fill_paletteer_c("pals::kovesi.linear_bgy_10_95_c74", direction = 1) + # this is okay
  paletteer::scale_fill_paletteer_c("viridis::viridis", direction = 1) + # this is perfect
  scale_x_discrete(expand = c(0, 0)) + # No space for X axis
  scale_y_continuous(trans = 'reverse', breaks = 1:28, labels = 1:28, expand = c(0, 0)) + # No space for Y axis
  geom_vline(xintercept = 5.5, size = 0.7, color = "black") + # Thick line between V5 and V6
  geom_vline(xintercept = 12.5, size = 0.7, color = "black") + # Thick line between V13 and V14
  #coord_fixed(ratio = 1) + # This ensures that tiles are square if that's desired
  theme_classic() + # Use a minimal theme
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), # Adjust the angle of x axis labels if needed
    axis.text.y = element_text(angle = 0), # Adjust the angle of y axis labels if needed
    panel.grid.major = element_blank(), # Remove major grid lines
    panel.grid.minor = element_blank(), # Remove minor grid lines
    panel.border = element_blank(), # Remove panel border
    plot.background = element_blank(), # Remove plot background
    panel.background = element_blank(), # Remove panel background
        legend.position = "bottom", # Move legend to bottom
    legend.direction = "horizontal" # Horizontal legend
  ) +
  labs(fill = "Conservation score") # Label for the legend
    #axis.ticks = element_blank() # Remove axis ticks
   
  #labs(title = "Heatmap with Custom Color Gradient", x = "Column", y = "Row", fill = "Value")

# Print the heatmap
print(heatmap_plot)
ggsave("../output/rcm/RCM_fagales.pdf", width = 3.7, height = 5)
```


####Load RCM output matrix for Vitales

```{r}
# Load necessary library
library(reshape2)

# Read the data from the file
file_path <- "../input/rcm/26_Vitales_rcm_score" 
rcm_vitales <- read.csv(file_path, header = FALSE, sep = ",", strip.white = TRUE)

# Convert the data frame to a vector of values
values <- as.numeric(unlist(rcm_vitales))

# Ensure the length of values is compatible with a 14x28 matrix
if (length(values) != 14*28) {
  stop("The number of values in the file does not match the expected size of a 14x28 matrix.")
}

# Reshape the vector into a matrix
matrix_rcm <- matrix(values, ncol = 14, byrow = TRUE)


# Optionally, write the matrix to a new CSV file if needed
write.csv(matrix_rcm, "../output/rcm/vitales_matrix_output.csv", row.names = FALSE)

```

####Plot the RCM plot for vitales

```{r}
# Load required libraries
library(ggplot2)
library(reshape2)  # For melt function
library(paletteer)

# Read the matrix data
matrix_rcm <- read.csv("../output/rcm/vitales_matrix_output.csv", header = TRUE)

# Create a new column 'Row' to preserve the row index before melting
matrix_rcm$Row <- seq_len(nrow(matrix_rcm))

# Melt the data for use with ggplot, with 'Row' as the id variable
matrix_melted <- melt(matrix_rcm, id.vars = 'Row')

# Define the color scale with blue for minimum and yellow for maximum
#blue_yellow_scale <- scale_fill_gradient2(low = "blue", mid = "green", high = "yellow", midpoint = 4, space = "Lab", transform = "identity")

# Create the heatmap
heatmap_plot <- ggplot(matrix_melted, aes(variable, Row, fill = value)) +
   geom_raster(interpolate = TRUE) +
  geom_tile(color = "darkgrey") +
  #blue_yellow_scale+
  #paletteer::scale_fill_paletteer_c("ggthemes::Orange-Blue Diverging", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::RdYlBu", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Spectral", direction = -1) +
 # paletteer::scale_fill_paletteer_c("oompaBase::blueyellow", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::topo.colors", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Plasma", direction = 1) +  # this is good
   #paletteer::scale_fill_paletteer_c("grDevices::ag_Sunset", direction = 1) +  # this is good
  # paletteer::scale_fill_paletteer_c("grDevices::YlOrRd", direction = 1) + # this is good
  #paletteer::scale_fill_paletteer_c("grDevices::YlGnBu", direction = 1) + # this is good
    #paletteer::scale_fill_paletteer_c("oompaBase::jetColors", direction = 1) + # this is perfect
    #paletteer::scale_fill_paletteer_c("pals::kovesi.linear_bgy_10_95_c74", direction = 1) + # this is okay
  paletteer::scale_fill_paletteer_c("viridis::viridis", direction = 1) + # this is perfect
  scale_x_discrete(expand = c(0, 0)) + # No space for X axis
  scale_y_continuous(trans = 'reverse', breaks = 1:28, labels = 1:28, expand = c(0, 0)) + # No space for Y axis
  geom_vline(xintercept = 5.5, size = 0.7, color = "black") + # Thick line between V5 and V6
  geom_vline(xintercept = 12.5, size = 0.7, color = "black") + # Thick line between V13 and V14
  #coord_fixed(ratio = 1) + # This ensures that tiles are square if that's desired
  theme_classic() + # Use a minimal theme
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), # Adjust the angle of x axis labels if needed
    axis.text.y = element_text(angle = 0), # Adjust the angle of y axis labels if needed
    panel.grid.major = element_blank(), # Remove major grid lines
    panel.grid.minor = element_blank(), # Remove minor grid lines
    panel.border = element_blank(), # Remove panel border
    plot.background = element_blank(), # Remove plot background
    panel.background = element_blank(), # Remove panel background
        legend.position = "bottom", # Move legend to bottom
    legend.direction = "horizontal" # Horizontal legend
  ) +
  labs(x = " ", y = "LRR", fill = "Conservation score") # Label for the legend
    #axis.ticks = element_blank() # Remove axis ticks
   
  #labs(title = "Heatmap with Custom Color Gradient", x = "Column", y = "Row", fill = "Value")

# Print the heatmap
print(heatmap_plot)
ggsave("../output/rcm/RCM_Vitales.pdf", width = 3.7, height = 5)
```

