  
```{r}
library(ggplot2)
library(zoo)
```


### Normalized Shanon Entropy
```{r}

entropy <- read.table('../input/entropylist.tsv',sep = '\t', header = TRUE)

# Define the custom ggplot theme
my_ggplot_theme <- theme_classic() +
  theme(text = element_text(size = 16),
        axis.title.x = element_text(size = 14, color = "black"),
        axis.title.y = element_text(size = 14, color = "black"),
        axis.text.x = element_text(size = 14, color = "black"),
        axis.text.y = element_text(size = 14, color = "black"),
        axis.ticks = element_line(size = 0.8))


# Create the plot with vertical lines at specified positions and apply the custom theme
p <- ggplot(filter(entropy, Order == "Rosales"), aes(x = Position, y = Entropy, color = Order)) +
    geom_line(size = 1.0) + # Adjust this value to make the line thicker
    #geom_smooth(se = FALSE, method = "loess", span = 0.1, color = "black") + # Add a smooth curve (change span for smoothness)
    geom_vline(xintercept = c(247, 391, 412, 439, 460), color = "red", alpha = 0.3) +
    geom_hline(yintercept = (1.5/log2(20)), col = "red") +
    my_ggplot_theme +
    scale_y_continuous(expand = c(0, 0), limits = c(0, 0.8)) + # Set y-axis max to 9
    scale_x_continuous(expand = c(0, 0), breaks = seq(100, 700, by = 100)) + # Set x-axis breaks at every 100 units
    labs(title = "Fagales",
         x = "Amino Acid Position",
         y = "Normalized Shannon Entropy")

# Save the plot to a file
ggsave("../output/Fagales_entropy.pdf", plot = p, width = 10, height = 5, dpi = 300)

# Print the plot to the R console
print(p)

```


#### Combined Curves
```{r}
library(ggplot2)
library(zoo)
library(dplyr)

# Function to read data and calculate sliding average
read_and_smooth <- function(file_path, window_size) {
  # Read the CSV file
  omega <- read.csv(file_path)
  
  # Calculate the sliding window average
  omega$Sliding_Average <- zoo::rollapply(omega$dN.dS, 
                                           width = window_size, 
                                           by = 1, 
                                           FUN = mean, 
                                           align = 'center', 
                                           fill = NA)
  # Add a column for the group (file identifier)
  omega$Group <- gsub(".*?/(.*)\\.csv$", "\\1", file_path)
  
  return(omega)
}

# Define the window size for smoothing
window_size <- 55

# Read and smooth data from all CSV files
files <- c("../input/fagales_omega.csv", "../input/brassicales_omega.csv", "../input/rosales_omega.csv")
omega_data <- lapply(files, function(f) read_and_smooth(f, window_size))

# Combine all data frames into one
omega_data_combined <- do.call(rbind, omega_data)

write.csv(omega_data_combined, file = "../output/combined_omega.csv")

# Define the custom ggplot theme
my_ggplot_theme <- theme_linedraw() +
  theme(text = element_text(size = 16),
        axis.title.x = element_text(size = 14, color = "black"),
        axis.title.y = element_text(size = 14, color = "black"),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 14, color = "black"),
        axis.ticks = element_line(size = 0.8),
        axis.ticks.length.y = unit(1.5, "mm"),
        plot.background = element_rect(fill = "white"),
        panel.grid = element_blank(), 
        panel.border = element_rect(color = "black", size = 0.8))

# Create the plot with smooth curves for each dataset
p <- ggplot(omega_data_combined, aes(x = pos, y = Sliding_Average, color = Group)) +
  #geom_line(size = 1.1) + 
  #geom_smooth(se = FALSE, method = "loess", span = 0.3) +
  geom_line(size = 1) + 
  #geom_smooth(se = FALSE, method = "loess", span = 0.01) +
  my_ggplot_theme +
  scale_x_continuous(expand = c(0,0), breaks = seq(100, 700, by = 100)) +
  #scale_y_continuous(limits = c(0.18, 0.59))+
  labs(title = "dN/dS Across Plant orders",
       x = "Amino Acid Position",
       y = " dN/dS",
       color = "Plant order") +  # Update the legend title
  scale_color_manual(values = c( "#66C2A5", "#C84D4C","#8DA0CB", "#D55E00"),
                     labels = c("Brassicales order", "Fagales order", "Rosales order"))  # Update the legend labels

# Save the plot to a file
ggsave("../output/combined_omega_curves.pdf", plot = p, width = 13, height = 4, dpi = 300)

# Print the plot to the R console
print(p)

```

```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)

# Load the data
fagales <- read.csv("../input/fagales_omega.csv")
rosales <- read.csv("../input/rosales_omega.csv")
brassicales <- read.csv("../input/brassicales_omega.csv")

# Define a function to calculate the distribution of dN/dS > 1 across regions
calculate_distribution <- function(data, regions) {
  distribution <- numeric(length(regions) - 1)
  total_high_dn_ds <- sum(data$dN.dS > 1)
  for (i in 1:(length(regions) - 1)) {
    count <- sum(data$dN.dS[data$pos >= regions[i] & data$pos < regions[i + 1]] > 1)
    portion <- ifelse(total_high_dn_ds > 0, count / total_high_dn_ds, 0)
    distribution[i] <- portion
  }
  return(distribution)
}

# Define the custom ggplot theme
my_ggplot_theme <- theme_classic() +
  theme(text = element_text(size = 16),
        axis.title.x = element_text(size = 14, color = "black"),
        axis.title.y = element_text(size = 14, color = "black"),
        axis.text.x = element_text(size = 14, color = "black"),
        axis.text.y = element_text(size = 14, color = "black"),
        axis.ticks = element_line(size = 0.8))


# Define the regions for each dataset (add an upper bound to the last region based on your data)
fagales_regions <- c(72, 96, 123, 144, 168, 192, 216, 240, 264, 288, 312, 336, 360, 384, 408, 432, 456, 480, 504, 528, 552, 576, 603, 626, 650, 675, 699, 723, max(fagales_data$pos) + 1)
rosales_regions <- c(72, 96, 123, 144, 168, 192, 216, 240, 264, 288, 312, 336, 360, 384, 408, 432, 456, 480, 504, 528, 552, 576, 603, 626, 653, 678, 699, 723, max(rosales_data$pos) + 1)
brassicales_regions <- c(72, 96, 123, 144, 168, 192, 216, 240, 264, 288, 312, 336, 360, 387, 411, 435, 459, 483, 507, 531, 555, 579, 605, 629, 653, 680, 705, 729, max(brassicales_data$pos) + 1)

# Calculate distributions
fagales_dist <- calculate_distribution(fagales, fagales_regions)
rosales_dist <- calculate_distribution(rosales, rosales_regions)
brassicales_dist <- calculate_distribution(brassicales, brassicales_regions)

# Calculate average distribution
average_dist <- (fagales_dist + rosales_dist + brassicales_dist) / 3

# Prepare data for ggplot
regions <- as.factor(1:28)
data <- data.frame(regions, fagales_dist, rosales_dist, brassicales_dist, average_dist)

# Melt the data for ggplot
data_melted <- melt(data, id.vars = 'regions')

distribution <- ggplot() +
  geom_bar(data = data_melted[data_melted$variable != "average_dist", ], 
           aes(x = regions, y = value, fill = variable), 
           stat = "identity", position = position_dodge(width = 0.5), alpha = 0.8) +
  geom_line(data = data.frame(regions, average_dist = average_dist), 
            aes(x = regions, y = average_dist, group = 1), color = "black", size = 0.7, alpha = 0.5) +
  #geom_point(data = data.frame(regions, average_dist = average_dist), 
            # aes(x = regions, y = average_dist), color = "black", size = 2) +
  labs(x = "LRR", y = "Normalized distribution of omega > 1 residue") +
  scale_x_discrete(breaks = regions) +
  scale_y_continuous(expand = c(0, 0))+
  scale_fill_manual(values = c("fagales_dist" = "#FC8D62", "rosales_dist" = "#8DA0CB", "brassicales_dist" = "#66C2A5")) +
  my_ggplot_theme 

print(distribution)
# Save the plot to a file
ggsave("../output/distribution_plot.pdf", plot = distribution, width = 13, height = 4, dpi = 300)


```



```{r}
write.csv(omega_data_combined, file = "../output/combined_omega.csv")
```


####Plot dN/dS at region 1
```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)

# Read the data
data <- read.csv("../output/combined_omega.csv")

# Function to extract data for a specified range and group
extract_data <- function(data, group_name, start_pos, end_pos) {
  data %>%
    filter(Group == group_name & pos >= start_pos & pos <= end_pos) %>%
    mutate(relative_pos = pos - start_pos + 1) # Create a new column for relative position (1 to 24)
}

# Define ranges for each group
fagales_range <- c(216, 263)
brassicales_range <- c(219, 266)
rosales_range <- c(216, 263)

# Extract data for each range
fagales_data_region_1 <- extract_data(data, "input/fagales_omega", fagales_range[1], fagales_range[2])
brassicales_data_region_1 <- extract_data(data, "input/brassicales_omega", brassicales_range[1], brassicales_range[2])
rosales_data_region_1 <- extract_data(data, "input/rosales_omega", rosales_range[1], rosales_range[2])

# Combine extracted data and set custom colors
combined_data <- rbind(
  fagales_data_region_1 %>% mutate(Group = "Fagales"),
  brassicales_data_region_1 %>% mutate(Group = "Brassicales"),
  rosales_data_region_1 %>% mutate(Group = "Rosales")
) %>% 
  mutate(color = ifelse(`dN.dS` > 1, case_when(
    Group == "Brassicales" ~ "#66C2A5",
    Group == "Fagales" ~ "#C84D4C",
    Group == "Rosales" ~ "#8DA0CB"
  ), case_when(
    Group == "Brassicales" ~ "gray75",
    Group == "Fagales" ~ "gray73",
    Group == "Rosales" ~ "gray77"
  )))

# Plot with custom color rules and a red line for dN/dS = 1
ggplot(combined_data, aes(x = relative_pos, y = `dN.dS`, fill = color)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.85) +
  geom_hline(yintercept = 1, color = "red", linetype = "dashed") +
  scale_fill_identity() + # Use the actual colors specified in the data frame
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 11, 25, 35, 48), labels = c("0"," ", "25", " ", "48")) +
  scale_y_continuous(expand = c(0, 0)) + # Remove padding in y-axis
  labs(x = "Amino Acid Position", y = "Posterior mean omega" )+
  theme_classic() +
   theme(legend.position = "right",
         axis.text.x = element_text(size = 15, color = "black"),
        axis.text.y = element_text(size = 15, color = "black"),
        axis.title.y = element_text(size = 15, color = "black"),
        axis.title.x = element_blank())
ggsave("../output/omega_region_1.pdf", width = 6, height = 3)

```

####Region 2
```{r}
# Define ranges for each group
fagales_range <- c(411, 458)
brassicales_range <- c(408, 455)
rosales_range <- c(411, 458)

# Extract data for each range
fagales_data_region_2 <- extract_data(data, "input/fagales_omega", fagales_range[1], fagales_range[2])
brassicales_data_region_2 <- extract_data(data, "input/brassicales_omega", brassicales_range[1], brassicales_range[2])
rosales_data_region_2 <- extract_data(data, "input/rosales_omega", rosales_range[1], rosales_range[2])

# Combine extracted data and set custom colors
combined_data <- rbind(
  fagales_data_region_2 %>% mutate(Group = "Fagales"),
  brassicales_data_region_2 %>% mutate(Group = "Brassicales"),
  rosales_data_region_2 %>% mutate(Group = "Rosales")
) %>% 
  mutate(color = ifelse(`dN.dS` > 1, case_when(
    Group == "Brassicales" ~ "#66C2A5",
    Group == "Fagales" ~ "#C84D4C",
    Group == "Rosales" ~ "#8DA0CB"
  ), case_when(
    Group == "Brassicales" ~ "gray75",
    Group == "Fagales" ~ "gray73",
    Group == "Rosales" ~ "gray77"
  )))

# Plot with custom color rules and a red line for dN/dS = 1
ggplot(combined_data, aes(x = relative_pos, y = `dN.dS`, fill = color)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.85) +
  geom_hline(yintercept = 1, color = "red", linetype = "dashed") +
  scale_fill_identity() + # Use the actual colors specified in the data frame
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 11, 25, 35, 48), labels = c("0"," ", "25", " ", "48")) +
  scale_y_continuous(expand = c(0, 0)) + # Remove padding in y-axis
  labs(x = "Amino Acid Position", y = "Posterior mean omega" )+
  theme_classic() +
   theme(legend.position = "right",
         axis.text.x = element_text(size = 15, color = "black"),
        axis.text.y = element_text(size = 15, color = "black"),
        axis.title.y = element_text(size = 15, color = "black"),
        axis.title.x = element_blank())
ggsave("../output/omega_region_2.pdf",  width = 6, height = 3)

```

####Load RCM output matrix

```{r}
# Load necessary library
library(reshape2)

# Read the data from the file
file_path <- "../input/until Carpinus_viminea.txt" # Replace path_to_your_file with the actual path
rcm_qv <- read.csv(file_path, header = FALSE, sep = ",", strip.white = TRUE)

# Convert the data frame to a vector of values
values <- as.numeric(unlist(rcm))

# Ensure the length of values is compatible with a 14x28 matrix
if (length(values) != 14*28) {
  stop("The number of values in the file does not match the expected size of a 14x28 matrix.")
}

# Reshape the vector into a matrix
matrix_rcm_qv <- matrix(values, ncol = 14, byrow = TRUE)

# If you need to manipulate or analyze the matrix, you can do so here.

# Optionally, write the matrix to a new CSV file if needed
write.csv(matrix_rcm_qv, "../output/rcm_qv_matrix_output.csv", row.names = FALSE)

```

####Plot the RCM plot for Qv

```{r}
# Load required libraries
library(ggplot2)
library(reshape2)  # For melt function
library(paletteer)

# Read the matrix data
matrix_rcm_qv <- read.csv("../output/matrix_output.csv", header = TRUE)

# Create a new column 'Row' to preserve the row index before melting
matrix_rcm_qv$Row <- seq_len(nrow(matrix_rcm_qv))

# Melt the data for use with ggplot, with 'Row' as the id variable
matrix_rcm_qv_melted <- melt(matrix_rcm_qv, id.vars = 'Row')

# Define the color scale with blue for minimum and yellow for maximum
#blue_yellow_scale <- scale_fill_gradient2(low = "blue", mid = "green", high = "yellow", midpoint = 4, space = "Lab", transform = "identity")

# Create the heatmap
heatmap_plot <- ggplot(matrix_rcm_qv_melted, aes(variable, Row, fill = value)) +
   geom_raster(interpolate = TRUE) +
  geom_tile(color = "darkgrey") +
  #blue_yellow_scale+
  #paletteer::scale_fill_paletteer_c("ggthemes::Orange-Blue Diverging", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::RdYlBu", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Spectral", direction = -1) +
 # paletteer::scale_fill_paletteer_c("oompaBase::blueyellow", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::topo.colors", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Plasma", direction = 1) +  # this is good
   #paletteer::scale_fill_paletteer_c("grDevices::ag_Sunset", direction = 1) +  # this is good
  # paletteer::scale_fill_paletteer_c("grDevices::YlOrRd", direction = 1) + # this is good
  #paletteer::scale_fill_paletteer_c("grDevices::YlGnBu", direction = 1) + # this is good
    #paletteer::scale_fill_paletteer_c("oompaBase::jetColors", direction = 1) + # this is perfect
    #paletteer::scale_fill_paletteer_c("pals::kovesi.linear_bgy_10_95_c74", direction = 1) + # this is okay
  paletteer::scale_fill_paletteer_c("viridis::viridis", direction = 1) + # this is perfect
  scale_x_discrete(expand = c(0, 0)) + # No space for X axis
  scale_y_continuous(trans = 'reverse', breaks = 1:28, labels = 1:28, expand = c(0, 0)) + # No space for Y axis
  geom_vline(xintercept = 6.5, size = 0.7, color = "black") + # Thick line between V6 and V7
  geom_vline(xintercept = 12.5, size = 0.7, color = "black") + # Thick line between V13 and V14
  #coord_fixed(ratio = 1) + # This ensures that tiles are square if that's desired
  theme_classic() + # Use a minimal theme
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), # Adjust the angle of x axis labels if needed
    axis.text.y = element_text(angle = 0), # Adjust the angle of y axis labels if needed
    panel.grid.major = element_blank(), # Remove major grid lines
    panel.grid.minor = element_blank(), # Remove minor grid lines
    panel.border = element_blank(), # Remove panel border
    plot.background = element_blank(), # Remove plot background
    panel.background = element_blank(), # Remove panel background
        legend.position = "bottom", # Move legend to bottom
    legend.direction = "horizontal" # Horizontal legend
  ) +
  labs(fill = "Conservation score") # Label for the legend
    #axis.ticks = element_blank() # Remove axis ticks
   
  #labs(title = "Heatmap with Custom Color Gradient", x = "Column", y = "Row", fill = "Value")

# Print the heatmap
print(heatmap_plot)
ggsave("../output/RCM_Qv.pdf", width = 3.7, height = 5)
```


####Load RCM output matrix for XL

```{r}
# Load necessary library
library(reshape2)

# Read the data from the file
file_path <- "../input/14_vitales_rcm_scores.txt" # Replace path_to_your_file with the actual path
rcm <- read.csv(file_path, header = FALSE, sep = ",", strip.white = TRUE)

# Convert the data frame to a vector of values
values <- as.numeric(unlist(rcm))

# Ensure the length of values is compatible with a 14x28 matrix
if (length(values) != 14*28) {
  stop("The number of values in the file does not match the expected size of a 14x28 matrix.")
}

# Reshape the vector into a matrix
matrix_rcm <- matrix(values, ncol = 14, byrow = TRUE)

# If you need to manipulate or analyze the matrix, you can do so here.

# Optionally, write the matrix to a new CSV file if needed
write.csv(matrix_rcm, "../output/matrix_output.csv", row.names = FALSE)

```
####Plot the RCM plot for XL

```{r}
# Load required libraries
library(ggplot2)
library(reshape2)  # For melt function
library(paletteer)

# Read the matrix data
matrix_rcm <- read.csv("../output/matrix_output.csv", header = TRUE)

# Create a new column 'Row' to preserve the row index before melting
matrix_rcm$Row <- seq_len(nrow(matrix_rcm))

# Melt the data for use with ggplot, with 'Row' as the id variable
matrix_melted <- melt(matrix_rcm, id.vars = 'Row')

# Define the color scale with blue for minimum and yellow for maximum
#blue_yellow_scale <- scale_fill_gradient2(low = "blue", mid = "green", high = "yellow", midpoint = 4, space = "Lab", transform = "identity")

# Create the heatmap
heatmap_plot <- ggplot(matrix_melted, aes(variable, Row, fill = value)) +
   geom_raster(interpolate = TRUE) +
  geom_tile(color = "darkgrey") +
  #blue_yellow_scale+
  #paletteer::scale_fill_paletteer_c("ggthemes::Orange-Blue Diverging", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::RdYlBu", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Spectral", direction = -1) +
 # paletteer::scale_fill_paletteer_c("oompaBase::blueyellow", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::topo.colors", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Plasma", direction = 1) +  # this is good
   #paletteer::scale_fill_paletteer_c("grDevices::ag_Sunset", direction = 1) +  # this is good
  # paletteer::scale_fill_paletteer_c("grDevices::YlOrRd", direction = 1) + # this is good
  #paletteer::scale_fill_paletteer_c("grDevices::YlGnBu", direction = 1) + # this is good
    #paletteer::scale_fill_paletteer_c("oompaBase::jetColors", direction = 1) + # this is perfect
    #paletteer::scale_fill_paletteer_c("pals::kovesi.linear_bgy_10_95_c74", direction = 1) + # this is okay
  paletteer::scale_fill_paletteer_c("viridis::viridis", direction = 1) + # this is perfect
  scale_x_discrete(expand = c(0, 0)) + # No space for X axis
  scale_y_continuous(trans = 'reverse', breaks = 1:28, labels = 1:28, expand = c(0, 0)) + # No space for Y axis
  geom_vline(xintercept = 6.5, size = 0.7, color = "black") + # Thick line between V6 and V7
  geom_vline(xintercept = 12.5, size = 0.7, color = "black") + # Thick line between V13 and V14
  #coord_fixed(ratio = 1) + # This ensures that tiles are square if that's desired
  theme_classic() + # Use a minimal theme
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), # Adjust the angle of x axis labels if needed
    axis.text.y = element_text(angle = 0), # Adjust the angle of y axis labels if needed
    panel.grid.major = element_blank(), # Remove major grid lines
    panel.grid.minor = element_blank(), # Remove minor grid lines
    panel.border = element_blank(), # Remove panel border
    plot.background = element_blank(), # Remove plot background
    panel.background = element_blank(), # Remove panel background
        legend.position = "bottom", # Move legend to bottom
    legend.direction = "horizontal" # Horizontal legend
  ) +
  labs(x = " ", y = "LRR", fill = "Conservation score") # Label for the legend
    #axis.ticks = element_blank() # Remove axis ticks
   
  #labs(title = "Heatmap with Custom Color Gradient", x = "Column", y = "Row", fill = "Value")

# Print the heatmap
print(heatmap_plot)
ggsave("../output/RCM_XL.pdf", width = 3.7, height = 5)
```


####Load RCM output matrix for Rosales

```{r}
# Load necessary library
library(reshape2)

# Read the data from the file
file_path <- "../input/Pmira.txt" # Replace path_to_your_file with the actual path
rcm <- read.csv(file_path, header = FALSE, sep = ",", strip.white = TRUE)

# Convert the data frame to a vector of values
values <- as.numeric(unlist(rcm))

# Ensure the length of values is compatible with a 14x28 matrix
if (length(values) != 14*28) {
  stop("The number of values in the file does not match the expected size of a 14x28 matrix.")
}

# Reshape the vector into a matrix
matrix_rcm <- matrix(values, ncol = 14, byrow = TRUE)

# If you need to manipulate or analyze the matrix, you can do so here.

# Optionally, write the matrix to a new CSV file if needed
write.csv(matrix_rcm, "../output/Rosales_matrix_output.csv", row.names = FALSE)

```

####Plot the RCM plot for Rosales

```{r}
# Load required libraries
library(ggplot2)
library(reshape2)  # For melt function
library(paletteer)

# Read the matrix data
matrix_rcm <- read.csv("../output/Rosales_matrix_output.csv", header = TRUE)

# Create a new column 'Row' to preserve the row index before melting
matrix_rcm$Row <- seq_len(nrow(matrix_rcm))

# Melt the data for use with ggplot, with 'Row' as the id variable
matrix_melted <- melt(matrix_rcm, id.vars = 'Row')

# Define the color scale with blue for minimum and yellow for maximum
#blue_yellow_scale <- scale_fill_gradient2(low = "blue", mid = "green", high = "yellow", midpoint = 4, space = "Lab", transform = "identity")

# Create the heatmap
heatmap_plot <- ggplot(matrix_melted, aes(variable, Row, fill = value)) +
   geom_raster(interpolate = TRUE) +
  geom_tile(color = "darkgrey") +
  #blue_yellow_scale+
  #paletteer::scale_fill_paletteer_c("ggthemes::Orange-Blue Diverging", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::RdYlBu", direction = -1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Spectral", direction = -1) +
 # paletteer::scale_fill_paletteer_c("oompaBase::blueyellow", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::topo.colors", direction = 1) +
  #paletteer::scale_fill_paletteer_c("grDevices::Plasma", direction = 1) +  # this is good
   #paletteer::scale_fill_paletteer_c("grDevices::ag_Sunset", direction = 1) +  # this is good
  # paletteer::scale_fill_paletteer_c("grDevices::YlOrRd", direction = 1) + # this is good
  #paletteer::scale_fill_paletteer_c("grDevices::YlGnBu", direction = 1) + # this is good
    #paletteer::scale_fill_paletteer_c("oompaBase::jetColors", direction = 1) + # this is perfect
    #paletteer::scale_fill_paletteer_c("pals::kovesi.linear_bgy_10_95_c74", direction = 1) + # this is okay
  paletteer::scale_fill_paletteer_c("viridis::viridis", direction = 1) + # this is perfect
  scale_x_discrete(expand = c(0, 0)) + # No space for X axis
  scale_y_continuous(trans = 'reverse', breaks = 1:28, labels = 1:28, expand = c(0, 0)) + # No space for Y axis
  geom_vline(xintercept = 6.5, size = 0.7, color = "black") + # Thick line between V6 and V7
  geom_vline(xintercept = 12.5, size = 0.7, color = "black") + # Thick line between V13 and V14
  #coord_fixed(ratio = 1) + # This ensures that tiles are square if that's desired
  theme_classic() + # Use a minimal theme
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), # Adjust the angle of x axis labels if needed
    axis.text.y = element_text(angle = 0), # Adjust the angle of y axis labels if needed
    panel.grid.major = element_blank(), # Remove major grid lines
    panel.grid.minor = element_blank(), # Remove minor grid lines
    panel.border = element_blank(), # Remove panel border
    plot.background = element_blank(), # Remove plot background
    panel.background = element_blank(), # Remove panel background
        legend.position = "bottom", # Move legend to bottom
    legend.direction = "horizontal" # Horizontal legend
  ) +
  labs(x = " ", y = "LRR", fill = "Conservation score") # Label for the legend
    #axis.ticks = element_blank() # Remove axis ticks
   
  #labs(title = "Heatmap with Custom Color Gradient", x = "Column", y = "Row", fill = "Value")

# Print the heatmap
print(heatmap_plot)
ggsave("../output/RCM_Rosales.pdf", width = 3.7, height = 5)
```

